### ISSUE TITLE
Show API version on top nav bar

### ISSUE THREAD

**Issue by sbastn** [aetrion/dnsimple-developer#33]
It would be cool if we could show the API version like this:
<img width="971" alt="screen shot 2015-10-08 at 7 55 53 pm" src="https://cloud.githubusercontent.com/assets/80610/10375044/a20e2cfa-6df6-11e5-972c-dbaa3a9c98ca.png">

Thoughts?

**Comment by weppos** [comment]
It may be something worth to consider once we'll publicly release the docs for v2.

**Comment by weppos** [comment]
Closing for now, as I added the API info in the sidebar.
