### ISSUE TITLE
API v0 expiration year

### ISSUE THREAD

**Issue by sbastn** [aetrion/dnsimple-developer#37]
The section http://developer.dnsimple.com/v1/#current-version is missing the expiration year for v0.

> The legacy API (called v0) will no longer be available after June 30th. Please switch to API v1 as soon as possible. Read the versioned API announcement for more details.

Add the expiration year after June 30th.

**Comment by weppos** [comment]
@sbastn actually, V0 is gone. We can probably remove that line completely.
