### ISSUE TITLE
OAuth client secret cannot be kept secret on mobile applications

### ISSUE THREAD

**Issue by 3flex** [aetrion/dnsimple-developer#49]
In mobile applications it is not possible to keep an OAuth client secret a secret, as it must be hardcoded into the application code. It is trivial to extract hard coded strings from a mobile application.

The draft DNSimple v2 OAuth documentation says "The client secret should not be shared." Given this is impossible for a mobile application, does the DNSimple OAuth implementation prevent supporting a mobile application? Or does the word "should" mean this is a recommendation that can be ignored for mobile apps?

Interested to know how the official iOS DNSimple app might change it's authentication flow for v2 as well.

Thanks!

**Comment by weppos** [comment]
The flow you are mentioning is the web app flow. In this case, the assumption is that the secret holder is an environment where the secret is not compromised.

When you redistribute an app, even if compiled, I agree that the secret could be spoofed (either looking at the HTTP log or disassembling the app).

There will likely be a second flow, which is not available yet, where the client will be able to negotiate an access token by sending a request authenticated using the basic auth and account username/password, along with the necessary OTP token (if the account is protected via 2FA).

The details are not defined yet. The idea is that the request should be sent once, without saving the user credentials (they should be collected and just used to generate the access token). Subsequent requests should use the negotiated access token.

Does it make sense to you? Do you have an existing use case (e.g. an app) that would be affected?

**Comment by 3flex** [comment]
Makes sense, and if that's implemented then that would presumably be recommended over the OAuth method for native apps.

I wasn't sure what was planned, since the v2 authentication docs list HTTP Basic (not suitable for native apps since user/pass must be stored) and the domain token method which doesn't give full access to an account, as the only alternatives to OAuth.

I'm building an Android app for DNSimple. For v1 API I'm using the recommended DNSimple API Token method but that's not shown as an option for v2 so I was exploring OAuth instead.

**Comment by weppos** [comment]
> and if that's implemented then that would presumably be recommended over the OAuth method for native apps.

Yes, for any app where the secret can be intercepted or decoded.

> I wasn't sure what was planned, since the v2 authentication docs list HTTP Basic (not suitable for native apps since user/pass must be stored) and the domain token method which doesn't give full access to an account, as the only alternatives to OAuth.

In http://developer.dnsimple.com/v2/oauth/ there will likely be a second section called non-web flows. The ose of Oauth doesn't exclude basic auth (they are different mechanism, for example we could potentially allow you to reuse an Oauth token via Basic Auth).

I assume the flow will be ready for our Public Beta, which means by the end of Q1. The current milestone (Developer Preview) that was completed on Dec 2015 didn't have this flow as requirement.

Another option, is that the user can create a token manually and you can request the token. This is not idea, but it may allow you to proceed with the development with the assumption you client only have to use an access token (and implement the token negotiation later on when the flow will be available).

> I'm building an Android app for DNSimple. For v1 API I'm using the recommended DNSimple API Token method but that's not shown as an option for v2 so I was exploring OAuth instead.

This is interesting. If you want to share your milestone or other details with us, just send an email to support@dnsimple.com. We can help you to get it done on V2 directly by giving you access to it, to avoid migrating to the new API version later on.

**Comment by 3flex** [comment]
Sounds good. I wouldn't be able obtain an OAuth token to reuse with basic auth from within the app since I'd have to use OAuth to get the token in the first place (unless I'm missing something?). Using user/password (+ optional 2FA token) to obtain the access token without using OAuth is probably best, as long as there's still a method to revoke access in the web UI.

I'll close this for now and open another issue for tracking that feature just for my own reference if that's OK, and I'll reach out via email to get access to the v2 API - makes sense to target that and aim to release the app sometime in Q2.

Thanks!
