### ISSUE TITLE
v2: Authentication for non-web apps

### ISSUE THREAD

**Issue by 3flex** [aetrion/dnsimple-developer#50]
Request for this to be implemented in the API:
> the client will be able to negotiate an access token by sending a request authenticated using the basic auth and account username/password, along with the necessary OTP token (if the account is protected via 2FA).

Refer https://github.com/aetrion/dnsimple-developer/issues/49#issuecomment-172586773.

**Comment by weppos** [comment]
@3flex we are tracking the development internally in a milestone. I'm closing this for now, as this repo is mostly focused on our docs.

I'll make sure to follow up with you on this particular feature.
