### ISSUE TITLE
v2: Which is correct "Update name servers" HTTP method?

### ISSUE THREAD

**Issue by 3flex** [aetrion/dnsimple-developer#53]
Doc says `PUT /:account/domains/:domain/name_servers` but the curl sample uses `POST`

In https://github.com/aetrion/dnsimple-developer/blob/master/content/v2/domains/name-servers.markdown

**Comment by weppos** [comment]
@3flex it should be a `PUT`. However, please note we're currently working on a few changes on that endpoint, and we'll also change the path (as part of a major update of all the name-server related endpoints: delegation, vanity name server and host registration).

I suggest you to not rely on it for now. We will complete the changes this week. I'll update this thread once the method will be reliable again.
