### ISSUE TITLE
vanity_name_servers endpoint not enabled

### ISSUE THREAD

**Issue by benbalter** [aetrion/dnsimple-developer#9]
Followed the instructions documention for [the `vanity_name_servers` endpoint](http://developer.dnsimple.com/domains/vanity-nameservers/), and even by copying and pasting the sample code, the respone from the endpoint is:

```json
{
    "errors": [
        "Feature not enabled"
    ]
}
```

If the feature is not yet enabled, it would be great to document that. If it is enabled, would be great to update the sample code. The response code is `HTTP/1.1 400 Bad Request`.

**Comment by jacegu** [comment]
I think that the update of [the documentation](http://developer.dnsimple.com/v1/nameservers/vanity-nameservers/) and the note make it sufficiently clear now.
